### ISSUE TITLE
Single thruster is not detected on first launch

### ISSUE THREAD

**Issue by duggerdufl** [uf-mil/SubjuGator#195]
Thruster with NID of 1 is not detected on the first launch of the sub from reboot. Relaunching the sub makes the thruster appear, and is detected on every subsequent launch until another reboot.

**Comment by mattlangford** [comment]
Maybe we could try resetting the ID to 8 like we tried briefly for the other thruster and seeing if it'll come up right away

**Comment by sentree** [comment]
Was this resolved at a past pool day?

**Comment by duggerdufl** [comment]
No, the problem still exists. Have not tested changing the ID yet.

**Comment by mattlangford** [comment]
Any progress here?

**Comment by DSsoto** [comment]
Currently trying to get thruster coms and diagnosis a little more stable but no we never figured out why.

**Comment by duggerdufl** [comment]
Let's write a couple lines into the thruster driver to log what was recieved and transmitted to a file so we can see what's happening, That's probably easier than trying to monitor a serial port directly.

Looks like only thruster ID 0 is returning any confirmation after a thrust command is sent. All the other thrusters stay silent but process and produce the thrust. All the thrusters are running identical firmware, so this is very strange.

**Comment by duggerdufl** [comment]
It does not look like we have problems detecting thruster ID 0 on the first launch anymore. Also confirmed that ID 0 is a valid ID for a thruster based on the VideoRay protocol reference. The VideoRay test tool still fails to get information for all thrusters except ID 0, however the ROS driver is able to get that data on all the thrusters. The commands sent from ROS and the test tool are similar, so this is still an open issue to be resolved.
